name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # -- Removed Render deploy step and its RENDER_DEPLOY_HOOK reference --

      # Step 1: Checkout your code (unchanged)
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Configure AWS Credentials (NEW: This replaces the Render deploy hook)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}       # Add this secret in GitHub
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   # Add this secret in GitHub
          aws-region: us-east-1                                        # Change to your AWS region if needed

      # Step 3: Install the Elastic Beanstalk CLI (NEW)
      - name: Install EB CLI
        run: pip install awsebcli

      # Step 4: Deploy to Elastic Beanstalk (NEW: This replaces the Render deployment step)
      - name: Deploy to Elastic Beanstalk
        run: |
          # Initialize the EB CLI with your application name and platform (Docker)
          eb init Fastapi-book-7 --platform docker --region us-east-1   # Replace "my-eb-app" with your EB application name
          # Deploy to your environment
          eb deploy Fastapi-book-7                                        # Replace "my-eb-env" with your EB environment name
