name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
              echo "Error: RENDER_DEPLOY_HOOK is not set. Please set it as a repository secret."
              exit 1
          fi
          echo "Triggering deploy using hook: $RENDER_DEPLOY_HOOK"
          curl -X POST "$RENDER_DEPLOY_HOOK"
